augment: true
augment_method: null
augment_times: 1
augment_times_query: 1

backbone:
  kwargs:
    is_feature: false
    is_flatten: false
    last_pool: true
    leaky_relu: false
    maxpool_last2: true
    negative_slope: 0.2
  name: Conv64F

batch_size: 128

classifier:
  kwargs:
    feat_dim: 640
    lambda_epi: 0.25
    num_classes: 200
    temperature: 0.2
    temperature_attn: 5.0
  name: RENet

includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/RENet.yaml
- backbones/Conv64F.yaml